# Live Plots

In [ ]:
import matplotlib.pyplot as plt
import os
import time

# Initialize lists to store data
sequence_numbers = []
error_values = []

# Function to read the last line of data from the file
def read_last_line():
    with open('data.txt', 'r') as file:
        last_line = file.readlines()[-1]
        seq, error = last_line.split()
        sequence_numbers.append(int(seq))
        error_values.append(float(error))

# Function to update the plot
def update_plot():
    plt.cla()  # Clear the current plot
    plt.plot(sequence_numbers, error_values, marker='o', color='b')
    plt.xlabel('Sequence Numbers')
    plt.ylabel('Error Values')
    plt.title('Live Plotting')
    plt.draw()
    plt.pause(0.01)

# Initial read of data
read_last_line()

# Create a figure and set the axis limits if needed
plt.figure()
plt.xlim(0, max(sequence_numbers))
plt.ylim(0, max(error_values))

# Continuously update the plot
while True:
    last_modification_time = os.path.getmtime('data.txt')
    if last_modification_time > os.path.getmtime('last_read.txt'):
        read_last_line()
        update_plot()
        os.utime('last_read.txt', None)
    time.sleep(0.5)  # Sleep for 1 second before checking again


# Reading data from the output file : 

In [4]:
import json
import jax.numpy as jnp

# File path
file_path = 'BatchOutput.json'

# Reading the data from the JSON file
with open(file_path, 'r') as json_file:
    loaded_data = json.load(json_file)

# Converting the data back to jax.numpy
loaded_A1 = jnp.array(loaded_data['A1'])
loaded_A2 = jnp.array(loaded_data['A2'])
loaded_B1 = jnp.array(loaded_data['B1'])
loaded_B2 = jnp.array(loaded_data['B2'])


In [5]:
print("upadated A1 : \n", loaded_A1, "\n")
print("upadated A2 : \n", loaded_A2, "\n")
print("upadated B1 : \n", loaded_B1, "\n")
print("upadated B2 : \n", loaded_B2, "\n")

upadated A1 : 
 [[-0.01215546 -0.01451929  0.018085    0.00858089]
 [ 0.06583627  0.18949625 -0.1453215  -0.11000742]
 [-0.09629517  0.42178407 -0.05345961 -0.2720382 ]
 [-0.00132495 -0.01822257 -0.00383879  0.02337275]] 

upadated A2 : 
 [[ 0.16158678 -0.16775472  0.00850138 -0.00233302]
 [ 0.03548642  0.2075174  -0.11720973 -0.12579134]
 [-0.08621297  0.5815387  -0.23538816 -0.259935  ]
 [-0.00383513 -0.00451945  0.0011101   0.00724324]] 

upadated B1 : 
 [ 9.7960674e-07 -4.0221485e-07  8.0719917e-07  2.5583964e-07] 

upadated B2 : 
 [-1.8113708e-06 -6.5930794e-07 -3.6648155e-06  5.3017352e-06] 



In [6]:
a = list(range(1,len(error_list_2)+1))

# Convergence
# for i in range(0, len(error_list_1)):

# plt.loglog(a, error_list_2, label = "",marker='o')
    
error_list_convergence = jnp.array(error_list_2)
error_list_convergence = jnp.log(error_list_convergence) / jnp.log(10)
plt.plot(a, error_list_convergence, label = "Error",marker='o')


plt.legend()
plt.grid()
plt.xlabel('Epoch')
plt.ylabel('Error')

NameError: name 'error_list_2' is not defined