In [2]:
import jax.numpy as jnp

x = jnp.array([1, 2, 3])
print(x)

[1 2 3]


In [3]:
from jax.config import config
config.update("jax_enable_x64", True)  #double precision

In [4]:
import jax.numpy as jnp

from skopt.space import Space
from skopt.sampler import Halton
from jax import jacfwd

# Special Transform Functions
from jax import grad, jit, vmap, pmap
import jax
from jax import jit

from jax._src.lax.utils import (
    _argnum_weak_type,
    _input_dtype,
    standard_primitive,)
from jax._src.lax import lax
from itertools import count
index = count()
from tqdm import tqdm, trange
# import prk_for_optimization as IRK4


In [5]:
from skopt.space import Space

In [6]:
spacedim = [(-0.5, 1.),(-0.5, 1.),(-0.5, 1.),(-0.5, 1.),(-0.5, 1.),(-0.5, 1.) ]

space = Space(spacedim)

halton = Halton()
n = 10

halton_sequence = halton.generate(space, n)
halton_sequence = jnp.array(halton_sequence)

print(halton_sequence)

[[-0.5        -0.5        -0.5        -0.5        -0.5        -0.5       ]
 [ 0.25        0.         -0.2        -0.28571429 -0.36363636 -0.38461538]
 [-0.125       0.5         0.1        -0.07142857 -0.22727273 -0.26923077]
 [ 0.625      -0.33333333  0.4         0.14285714 -0.09090909 -0.15384615]
 [-0.3125      0.16666667  0.7         0.35714286  0.04545455 -0.03846154]
 [ 0.4375      0.66666667 -0.44        0.57142857  0.18181818  0.07692308]
 [ 0.0625     -0.16666667 -0.14        0.78571429  0.31818182  0.19230769]
 [ 0.8125      0.33333333  0.16       -0.46938776  0.45454545  0.30769231]
 [-0.40625     0.83333333  0.46       -0.25510204  0.59090909  0.42307692]
 [ 0.34375    -0.44444444  0.76       -0.04081633  0.72727273  0.53846154]]
